### PR TITLE
Added new robinhood.py file for API Calling

### PR DESCRIPTION
**Pull request by carrycooldude**

### CODE REVIEW

**Review by ricardoprins — COMMENTED** [review]
This is a basic, standalone code, for an API. If you want to stick together to the project, the idea is to integrate this with the frontend - so, instead of having this like that, this should receive the input from the frontend (username, password - hence maybe adding a middleware to handle security in the future?)

What do you think?

**Comment by carrycooldude** [comment]
Okay can you give any resource for middleware one

**Comment by ricardoprins** [comment]
can you reach out to me either via whatsapp or discord?

**Comment by carrycooldude** [comment]
Yes can you share your discord id?

**Comment by ricardoprins** [comment]
Sure - TheRicardoPrins#4639

**Comment by ricardoprins** [comment]
Please reach out to me - closing this due to major revamp on backend!

**Pull request closed without merging**
